Repository openshift-kni/baremetal-deploy, pull requests merged in 2019-12, with the labels that each got.

#41 Add initial owners file to check the interaction with the ci robot
  features/sctp/OWNERS
Labels: needs-ok-to-test

#44 Add OWNER file
  OWNERS
  OWNERS_ALIASES
Labels: do-not-merge/invalid-owners-file, ok-to-test, size/M

#29 Add manifests and instructions how to enable the topology manager
  features/performance/README.md
  features/performance/manifests/05-fg-latency-sensetive.yaml
  features/performance/manifests/05-kubeletconfig-worker-rt.yaml
Labels: approved, lgtm

#36 Provide scripts to generate and deploy performance manifests
  .gitignore
  features/performance/Makefile
  features/performance/README.md
  features/performance/assets/rt-kernel-patch.sh
  features/performance/hack/common.sh
  features/performance/hack/deploy.sh
  features/performance/hack/generate.sh
  features/performance/manifests/05-mc-kargs-worker-rt.yaml
  features/performance/manifests/templates/00-tuned-network-latency.yaml.in
  features/performance/manifests/templates/11-machine-config-worker-rt-kernel.yaml.in
  features/performance/manifests/templates/12-fg-latency-sensetive.yaml.in
  features/performance/manifests/templates/12-kubeletconfig-worker-rt.yaml.in
  features/performance/manifests/templates/12-machine-config-worker-rt-kargs.yaml.in
  features/performance/manifests/templates/12-tuned-worker-rt.yaml.in
  features/rt/Makefile
  features/rt/README.md
  features/rt/hack/generate.sh
  features/rt/manifests/06-mc-rtkernel-worker-rt.yaml
Labels: approved, lgtm, size/L

#35 Support rt kernel updates
  features/performance/README.md
  features/performance/assets/rt-kernel-patch.sh
  features/performance/hack/generate.sh
  features/performance/manifests/templates/11-machine-config-worker-rt-kernel.yaml.in
Labels: approved, lgtm, size/M

#62 Makefile: add dummy targets for prow
  features/Makefile
Labels: approved, lgtm, size/XS

#63 Simplified CNF reviewers and approvers.
  OWNERS
  OWNERS_ALIASES
Labels: approved, lgtm, size/M

#53 Improved README
  README.md
Labels: lgtm, size/M

#64 Fixed cnf approvers
  OWNERS
  features/OWNERS
Labels: approved, lgtm, size/S

#37 apply rt machine config pool
  features/mcp/00-mcp-worker-rt.yaml
  features/mcp/README.md
Labels: lgtm, size/M

#61 Fixing #58
  features/performance/hack/deploy.sh
Labels: approved, lgtm, size/XS

#31 Deploy kubernetes-nmstate
  features/cnao/deploy.sh
  features/cnao/testing.sh
  features/kubernetes-nmstate/README.md
  features/kubernetes-nmstate/bond1.yaml
  features/kubernetes-nmstate/bond1_vlan.yaml
  features/kubernetes-nmstate/cnao-cr.yaml
  features/kubernetes-nmstate/deploy.sh
  features/kubernetes-nmstate/myenv.file
  features/kubernetes-nmstate/testing.sh
Labels: approved, lgtm, size/L

#56 performance: generator: ensure string
  features/performance/manifests/templates/12-kubeletconfig-worker-rt.yaml.in
Labels: approved, lgtm, size/XS

#60 Deploy the PTP operator using marketplace
  features/ptp/README.md
  features/ptp/deploy.sh
  features/ptp/deploy/01_namespace.yaml
  features/ptp/deploy/02_operator_group.yaml
  features/ptp/deploy/03_subscription.yaml
  features/ptp/myvars.example
  features/ptp/ptpconfig-grandmaster.yaml
  features/ptp/ptpconfig-slave.yaml
  features/ptp/test.sh
Labels: ok-to-test, size/L

#70 Added a link for nmstate in the README
  README.md
Labels: size/XS

#71 Improve unit test execution
  features/Makefile
  features/functests/test_suite_test.go
Labels: approved, lgtm, size/XS

#52 tests: bootstrap manifests tests
  .gitignore
  features/go.mod
  features/go.sum
  features/performance/hack/common.sh
  features/performance/hack/generate.sh
  features/performance/test/featuregate_test.go
  features/performance/test/kubeletconfig_test.go
  features/performance/test/machineconfig_test.go
  features/performance/test/test_suite_test.go
  features/performance/test/tuned_test.go
  features/vendor/github.com/onsi/ginkgo/extensions/table/table.go
  features/vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go
  features/vendor/github.com/openshift/cluster-node-tuning-operator/LICENSE
  features/vendor/github.com/openshift/cluster-node-tuning-operator/pkg/apis/tuned/register.go
  features/vendor/github.com/openshift/cluster-node-tuning-operator/pkg/apis/tuned/v1/doc.go
  features/vendor/github.com/openshift/cluster-node-tuning-operator/pkg/apis/tuned/v1/register.go
  features/vendor/github.com/openshift/cluster-node-tuning-operator/pkg/apis/tuned/v1/tuned_types.go
  features/vendor/github.com/openshift/cluster-node-tuning-operator/pkg/apis/tuned/v1/zz_generated.deepcopy.go
  features/vendor/gopkg.in/ini.v1/.gitignore
  features/vendor/gopkg.in/ini.v1/.travis.yml
  features/vendor/gopkg.in/ini.v1/LICENSE
  features/vendor/gopkg.in/ini.v1/Makefile
  features/vendor/gopkg.in/ini.v1/README.md
  features/vendor/gopkg.in/ini.v1/data_source.go
  features/vendor/gopkg.in/ini.v1/deprecated.go
  features/vendor/gopkg.in/ini.v1/error.go
  features/vendor/gopkg.in/ini.v1/file.go
  features/vendor/gopkg.in/ini.v1/helper.go
  features/vendor/gopkg.in/ini.v1/ini.go
  features/vendor/gopkg.in/ini.v1/key.go
  features/vendor/gopkg.in/ini.v1/parser.go
  features/vendor/gopkg.in/ini.v1/section.go
  features/vendor/gopkg.in/ini.v1/struct.go
  features/vendor/k8s.io/kubelet/LICENSE
  features/vendor/k8s.io/kubelet/config/v1beta1/doc.go
  features/vendor/k8s.io/kubelet/config/v1beta1/register.go
  features/vendor/k8s.io/kubelet/config/v1beta1/types.go
  features/vendor/k8s.io/kubelet/config/v1beta1/zz_generated.deepcopy.go
  features/vendor/modules.txt
Labels: approved, lgtm, size/XXL

#66 Make it possible to choose the features to run functests against
  features/Makefile
Labels: approved, lgtm, size/XS

#73 RT kernel script should exit with code 0 on success
  features/performance/assets/rt-kernel-patch.sh
Labels: approved, lgtm, size/XS

#59 Unify features generation and deployment
  features/Makefile
  features/cpumanager/README.adoc
  features/cpumanager/cpumanager-kubeletconfig.yml
  features/cpumanager/deploy.sh
  features/cpumanager/here
  features/cpumanager/pause-with-requests-deployment.yml
  features/cpumanager/reservedcpus/cpumanager-kubeletconfig.yml
  features/cpumanager/reservedcpus/deploy.sh
  features/cpumanager/reservedcpus/mc_isolcpus.yml
  features/hack/common.sh
  features/mcp/00-mcp-worker-rt.yaml
  features/mcp/deploy.sh
  features/performance/Makefile
  features/performance/README.md
  features/performance/deploy.sh
  features/performance/examples/cpu-stress-pod.yml
  features/performance/generate.sh
  features/performance/hack/common.sh
  features/performance/hack/deploy.sh
  features/performance/hack/generate.sh
  features/performance/test/test_suite_test.go
  features/sctp/deploy.sh
Labels: approved, lgtm, size/XL

#68 Adds a wait and overwrites the labels for sriov
  features/sriov/deploy.sh
Labels: approved, lgtm, size/S

#72 Consistency fixes
  features/performance/manifests/templates/12-feature-gate-latency-sensitive.yaml.in
  features/performance/manifests/templates/12-kubelet-config-worker-rt.yaml.in
  features/performance/test/featuregate_test.go
  features/performance/test/kubeletconfig_test.go
Labels: approved, lgtm, size/XS

#54 bonding: add configuration generation tool
  features/bonding/README.md
  features/bonding/examples/parameters.yaml.sample
  features/bonding/scripts/bonding.py
  features/bonding/templates/bondX-ignition.j2
  features/bonding/templates/ifcfg-bondX.j2
  features/bonding/templates/ifcfg-bondX.vlan.j2
  features/bonding/templates/ifcfg-iface.j2
  features/bonding/templates/nmstate-bondX.yaml.j2
Labels: ok-to-test, size/L

#38 Update install-steps.md
  install-steps.md
Labels: size/XXL

#74 Add the testing readme
  features/TESTING.md
Labels: approved, lgtm, size/M

#80 small typo
  install-steps.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#83 Add dockerfile for the OCP CI build image
  features/Dockefile.buildimage
Labels: approved, lgtm, size/S

#33 Add pre boot tuning operations
  features/functests/performance/performance.go
  features/functests/test_suite_test.go
  features/hack/common.sh
  features/performance/README.md
  features/performance/assets/pre-boot-tuning.sh
  features/performance/generate.sh
  features/performance/manifests/templates/11-pre-boot-worker-tuning.yaml.in
  features/performance/manifests/templates/12-machine-config-worker-rt-kargs.yaml.in
  features/performance/manifests/templates/12-tuned-worker-rt.yaml.in
  features/performance/test/featuregate_test.go
  features/performance/test/kubeletconfig_test.go
  features/performance/test/machineconfig_test.go
  features/performance/test/test_suite_test.go
  features/performance/test/tuned_test.go
Labels: approved, lgtm, size/L

#86 Add test env variable fixtures and fix build dockerfile
  features/Dockefile.buildimage
  features/hack/test_env.sh
Labels: approved, lgtm, size/S

#89 Remove the ginkgo makefile rule
  features/Makefile
Labels: approved, lgtm, size/XS

#90 Fix failing tests due to wrong initialization
  features/functests/performance/performance.go
Labels: approved, lgtm, size/S

#91 Put the --focus parameter before the folder, otherwise it's ignored.
  features/Makefile
Labels: approved, lgtm, size/XS

#85 Fix performance features deploy
  features/performance/README.md
  features/performance/assets/rt-kernel-patch.sh
  features/performance/deploy.sh
  features/performance/manifests/templates/12-kubelet-config-worker-rt.yaml.in
Labels: approved, lgtm, size/M

#93 Do not fail unblacklisting sctp when already done
  features/sctp/deploy.sh
Labels: approved, lgtm, size/XS

#94 Disable functests for performance until stable
  features/Makefile
Labels: approved, lgtm, size/XS

#92 Tiny doc fixes in performance dir
  README.md
  features/performance/README.md
  features/performance/deploy.sh
  features/performance/generate.sh
  features/performance/manifests/templates/12-machine-config-worker-rt-kargs.yaml.in
  features/performance/myvars.example
  features/performance/test/featuregate_test.go
  features/performance/test/kubeletconfig_test.go
  features/performance/test/machineconfig_test.go
  features/performance/test/test_suite_test.go
  features/performance/test/tuned_test.go
Labels: lgtm, size/M

#97 Removed microcode_ctl patch
  features/hack/common.sh
  features/performance/README.md
  features/performance/assets/rt-kernel-patch.sh
  features/performance/generate.sh
  features/performance/manifests/templates/11-machine-config-worker-rt-kernel.yaml.in
Labels: approved, lgtm, size/S

#99 update performance example nodeselector
  features/performance/examples/cpu-stress-pod.yml
  features/performance/examples/hugepages-pod.yaml
Labels: approved, lgtm, size/XS

#100 Functional tests - label one node as worker-rt
  features/Makefile
  features/hack/test_env.sh
Labels: approved, lgtm, size/XS

#87 Several updates/ feature adds
  README.md
  baremetal-prep/README.md
  baremetal-prep/baremetal-prep.sh
Labels: lgtm, size/L

#104 Provide a value for HUGEPAGES_NUMBER to be able to run the tests
  features/hack/test_env.sh
Labels: approved, lgtm, size/XS

#25 Add instructions on how to compile the installer
  hacks/build-baremetal-installer.md
Labels: lgtm, size/M

#95 Added dpdk example workload
  README.md
  features/dpdk/README.md
  features/dpdk/pktgen-pod.yaml
  features/dpdk/pktgen.dockerfile
  features/dpdk/testpmd-pod.yaml
  features/dpdk/testpmd.dockerfile
Labels: lgtm, size/L

#101 Documenting the copy of oc binary to a searchable path
  install-steps.md
Labels: lgtm, needs-ok-to-test, size/XS

#18 Use a custom sctp tester instead of the test_sctp executable
  features/functests/sctp/sctp.go
  features/sctp/README.md
  features/sctp/policy/newsctp.pp
  features/sctp/policy/sctp_policy_ds.yaml
  features/sctp/tester/Dockerfile
  features/sctp/tester/main.go
Labels: approved, lgtm, size/L

#116 Adjust test setup for functional tests
  features/Makefile
  features/hack/test_env.sh
Labels: approved, lgtm, size/XS

#107 Apply worker="" label only if not set already.
  features/performance/deploy.sh
Labels: approved, lgtm, ok-to-test, size/XS

#96 Fix pre boot script and perfomance tests
  features/Makefile
  features/functests/performance/performance.go
  features/performance/assets/pre-boot-tuning.sh
  features/performance/generate.sh
  features/performance/manifests/templates/11-pre-boot-worker-tuning.yaml.in
  features/performance/manifests/templates/12-machine-config-worker-rt-kargs.yaml.in
Labels: approved, lgtm, size/M

#115 Avoid double reboot under MCP scripts
  features/performance/README.md
  features/performance/assets/pre-boot-tuning.sh
  features/performance/assets/rt-kernel-patch.sh
  features/performance/deploy.sh
  features/performance/manifests/templates/10-machine-config-worker-rt-kargs.yaml.in
  features/performance/manifests/templates/11-machine-config-worker-rt-kernel.yaml.in
  features/performance/manifests/templates/11-pre-boot-worker-tuning.yaml.in
  features/performance/test/machineconfig_test.go
Labels: approved, lgtm, size/L

#98 kubernetes-nmstate:added node config examples to README.md
  features/kubernetes-nmstate/README.md
Labels: approved, lgtm, ok-to-test, size/M
