Repository openshift-kni/baremetal-deploy, pull requests merged in 2020-03, with the labels that each got.

#179 adding abays and sreichar as code reviewers
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#186 Change packages to check if present not latest
  ansible-ipi-install/roles/node-prep/tasks/30_req_packages.yml
Labels: approved, lgtm, ok-to-test, size/XS

#194 Ansible: RHCOS image caching support
  ansible-ipi-install/README.md
  ansible-ipi-install/inventory/hosts.sample
  ansible-ipi-install/roles/installer/defaults/main.yml
  ansible-ipi-install/roles/installer/library/podman_container.py
  ansible-ipi-install/roles/installer/tasks/23_rhcos_image_paths.yml
  ansible-ipi-install/roles/installer/tasks/24_rhcos_image_cache.yml
  ansible-ipi-install/roles/installer/tasks/25_create-install-config.yml
  ansible-ipi-install/roles/installer/tasks/30_create_metal3.yml
  ansible-ipi-install/roles/installer/tasks/35_customize_filesystem.yml
  ansible-ipi-install/roles/installer/tasks/main.yml
  ansible-ipi-install/roles/installer/templates/install-config.j2
  ansible-ipi-install/roles/installer/templates/metal3-config.j2
  ansible-ipi-install/roles/node-prep/tasks/100_power_off_cluster_servers.yml
  ansible-ipi-install/roles/node-prep/tasks/10_validation.yml
  ansible-ipi-install/roles/node-prep/tasks/70_enabled_fw_services.yml
  ansible-ipi-install/roles/node-prep/tasks/main.yml
Labels: approved, lgtm, ok-to-test, size/XXL

#188 fix package name
  ansible-ipi-install/README.md
Labels: approved, lgtm, size/XS

#196 Fixing Naming Inconsistencies
  install-steps.md
Labels: approved, lgtm, ok-to-test, size/M

#195 adding tags to all yml files, updating readme on how to use tags
  ansible-ipi-install/README.md
  ansible-ipi-install/roles/installer/tasks/10_get_oc.yml
  ansible-ipi-install/roles/installer/tasks/20_extract_installer.yml
  ansible-ipi-install/roles/installer/tasks/23_rhcos_image_paths.yml
  ansible-ipi-install/roles/installer/tasks/24_rhcos_image_cache.yml
  ansible-ipi-install/roles/installer/tasks/25_create-install-config.yml
  ansible-ipi-install/roles/installer/tasks/30_create_metal3.yml
  ansible-ipi-install/roles/installer/tasks/35_customize_filesystem.yml
  ansible-ipi-install/roles/installer/tasks/40_create_manifest.yml
  ansible-ipi-install/roles/installer/tasks/50_extramanifests.yml
  ansible-ipi-install/roles/installer/tasks/59_cleanup_bootstrap.yml
  ansible-ipi-install/roles/installer/tasks/60_deploy_ocp.yml
  ansible-ipi-install/roles/installer/tasks/70_cleanup_sub_man_registeration.yml
  ansible-ipi-install/roles/installer/tasks/main.yml
  ansible-ipi-install/roles/node-prep/tasks/100_power_off_cluster_servers.yml
  ansible-ipi-install/roles/node-prep/tasks/10_validation.yml
  ansible-ipi-install/roles/node-prep/tasks/20_sub_man_register.yml
  ansible-ipi-install/roles/node-prep/tasks/30_req_packages.yml
  ansible-ipi-install/roles/node-prep/tasks/40_bridge.yml
  ansible-ipi-install/roles/node-prep/tasks/50_modify_sudo_user.yml
  ansible-ipi-install/roles/node-prep/tasks/60_enabled_services.yml
  ansible-ipi-install/roles/node-prep/tasks/70_enabled_fw_services.yml
  ansible-ipi-install/roles/node-prep/tasks/80_libvirt_pool.yml
  ansible-ipi-install/roles/node-prep/tasks/90_create_config_install_dirs.yml
  ansible-ipi-install/roles/node-prep/tasks/main.yml
Labels: approved, lgtm, ok-to-test, size/L

#198 Install podman if required
  ansible-ipi-install/roles/node-prep/tasks/30_req_packages.yml
  ansible-ipi-install/roles/node-prep/vars/main.yml
Labels: approved, lgtm, size/S

#183 node-prep - make ipmi port configurable
  ansible-ipi-install/README.md
  ansible-ipi-install/inventory/hosts.sample
  ansible-ipi-install/roles/installer/templates/install-config.j2
  ansible-ipi-install/roles/node-prep/tasks/100_power_off_cluster_servers.yml
Labels: approved, lgtm, ok-to-test, size/M

#202 corrected extracting GA release instructions
  install-steps.md
Labels: approved, lgtm, ok-to-test, size/XS

#203 removed root priv from podman container creation
  ansible-ipi-install/roles/installer/tasks/24_rhcos_image_cache.yml
Labels: approved, lgtm, size/XS

#209 adding images to install-steps
  images/71_OpenShift_Baremetal_IPI_Depoyment_0320_1.png
  images/71_OpenShift_Baremetal_IPI_Depoyment_0320_2.png
  install-steps.md
Labels: approved, lgtm, size/S

#212 regathering network facts
  ansible-ipi-install/roles/node-prep/tasks/40_bridge.yml
Labels: approved, lgtm, ok-to-test, size/XS

#214 Added cache instructions
  install-steps.md
Labels: approved, lgtm, ok-to-test, size/M

#204 Get connection name for prov_nic
  ansible-ipi-install/roles/node-prep/tasks/40_bridge.yml
Labels: approved, lgtm, ok-to-test, size/S

#216 Fix and simplify cache downloads
  ansible-ipi-install/roles/installer/tasks/24_rhcos_image_cache.yml
Labels: approved, lgtm, ok-to-test, size/S

#217 removing requirement of raid-1
  install-steps.md
Labels: approved, lgtm, ok-to-test

#218 Pass unzipped qemu image sha256 to installer
  ansible-ipi-install/roles/installer/tasks/24_rhcos_image_cache.yml
Labels: approved, lgtm, size/XS

#220 UUID is empty due to incorrect nmcli command
  ansible-ipi-install/roles/node-prep/tasks/40_bridge.yml
Labels: approved, lgtm, ok-to-test, size/XS

#225 adding fail msgs when packages needed on control machine
  ansible-ipi-install/playbook.yml
  ansible-ipi-install/roles/node-prep/tasks/10_validation.yml
Labels: approved, lgtm, ok-to-test

#229 fixing python module dependencies
  ansible-ipi-install/playbook.yml
  ansible-ipi-install/roles/node-prep/tasks/10_validation.yml
Labels: approved, lgtm

#221 Ipv6
  ansible-ipi-install/inventory/hosts.sample
  ansible-ipi-install/roles/installer/templates/install-config.j2
  ansible-ipi-install/roles/node-prep/defaults/main.yml
  ansible-ipi-install/roles/node-prep/library/nmcli.py
  ansible-ipi-install/roles/node-prep/tasks/40_bridge.yml
Labels: approved, lgtm, size/M

#234 removing full path of templates
  ansible-ipi-install/roles/node-prep/tasks/80_libvirt_pool.yml
Labels: approved, lgtm, ok-to-test

#206 Validate and wrap IP addresses
  ansible-ipi-install/roles/installer/templates/install-config.j2
  ansible-ipi-install/roles/installer/templates/metal3-config.j2
Labels: approved, lgtm, ok-to-test, size/S

#237 fixing install-steps pieces documentation
  install-steps.md
Labels: approved, lgtm

#240 removing 5000 as default fw rule
  ansible-ipi-install/roles/node-prep/tasks/70_enabled_fw_services.yml
Labels: approved, lgtm, ok-to-test

#241 [doc] removing requirement of port 5000
  install-steps.md
Labels: approved, lgtm

#243 adding python module details to readme
  ansible-ipi-install/README.md
Labels: approved, lgtm

#246 removing ipaddr filter when using hostnames
  ansible-ipi-install/roles/installer/templates/install-config.j2
  ansible-ipi-install/roles/installer/templates/metal3-config.j2
Labels: approved, lgtm

#244 Only set extcidrnet if not provided
  ansible-ipi-install/roles/node-prep/tasks/40_bridge.yml
Labels: approved, lgtm

#205 Perform IPv6 lookups
  ansible-ipi-install/inventory/hosts.sample
  ansible-ipi-install/roles/node-prep/tasks/10_validation.yml
  ansible-ipi-install/roles/node-prep/vars/main.yml
Labels: approved, lgtm, ok-to-test, size/S

#247 Added chrony config via mco
  ansible-ipi-install/README.md
  ansible-ipi-install/inventory/hosts.sample
  ansible-ipi-install/roles/installer/tasks/50_extramanifests.yml
  ansible-ipi-install/roles/installer/templates/99-etc-chrony.conf.j2
  ansible-ipi-install/roles/installer/templates/chrony.conf.j2
Labels: approved, lgtm

#248 removing pub nic j2 as no longer in use
  ansible-ipi-install/README.md
  ansible-ipi-install/roles/node-prep/templates/pub_nic.j2
Labels: approved, lgtm

#201 Disconnected registry
  ansible-ipi-install/README.md
  ansible-ipi-install/inventory/hosts.sample
  ansible-ipi-install/roles/installer/defaults/main.yml
  ansible-ipi-install/roles/installer/tasks/15_disconnected_registry_create.yml
  ansible-ipi-install/roles/installer/tasks/15_disconnected_registry_existing.yml
  ansible-ipi-install/roles/installer/tasks/20_extract_installer.yml
  ansible-ipi-install/roles/installer/tasks/main.yml
  ansible-ipi-install/roles/installer/templates/install-config-appends.j2
  ansible-ipi-install/roles/installer/templates/install-config.j2
  ansible-ipi-install/roles/installer/vars/main.yml
  ansible-ipi-install/roles/node-prep/tasks/15_validation_disconnected_registry.yml
  ansible-ipi-install/roles/node-prep/tasks/main.yml
  ansible-ipi-install/roles/node-prep/vars/main.yml
Labels: approved, lgtm, ok-to-test, size/L

#236 [doc] Added disconnected registry to install steps
  install-steps.md
Labels: approved, lgtm

#250 fixing running playbook yml placement
  ansible-ipi-install/README.md
Labels: approved, lgtm

#253 fixing tree structure of README
  ansible-ipi-install/README.md
Labels: approved, lgtm

#255 Fix incorrect variable name
  ansible-ipi-install/roles/node-prep/library/nmcli.py
Labels: approved, lgtm, ok-to-test

#259 fixing inventory in README
  ansible-ipi-install/README.md
Labels: approved, lgtm

#258 Use tagged version of filetranspiler
  ansible-ipi-install/roles/installer/tasks/35_customize_filesystem.yml
Labels: approved, lgtm
