Repository openshift-kni/baremetal-deploy, pull requests merged in 2020-02, with the labels that each got.

#129 Ansible playbook to install IPI on baremetal nodes
  ansible-ipi-install/README.md
  ansible-ipi-install/ansible.cfg
  ansible-ipi-install/inventory/hosts.sample
  ansible-ipi-install/playbook.yml
  ansible-ipi-install/roles/installer/defaults/main.yml
  ansible-ipi-install/roles/installer/files/.gitkeep
  ansible-ipi-install/roles/installer/handlers/main.yml
  ansible-ipi-install/roles/installer/meta/main.yml
  ansible-ipi-install/roles/installer/tasks/10_get_oc.yml
  ansible-ipi-install/roles/installer/tasks/20_extract_installer.yml
  ansible-ipi-install/roles/installer/tasks/30_create_metal3.yml
  ansible-ipi-install/roles/installer/tasks/40_create_manifest.yml
  ansible-ipi-install/roles/installer/tasks/50_extramanifests.yml
  ansible-ipi-install/roles/installer/tasks/60_deploy_ocp.yml
  ansible-ipi-install/roles/installer/tasks/70_cleanup_sub_man_registeration.yml
  ansible-ipi-install/roles/installer/tasks/main.yml
  ansible-ipi-install/roles/installer/templates/metal3-config.j2
  ansible-ipi-install/roles/installer/tests/inventory
  ansible-ipi-install/roles/installer/tests/test.yml
  ansible-ipi-install/roles/installer/vars/main.yml
  ansible-ipi-install/roles/node-prep/defaults/main.yml
  ansible-ipi-install/roles/node-prep/handlers/main.yml
  ansible-ipi-install/roles/node-prep/library/nmcli.py
  ansible-ipi-install/roles/node-prep/meta/main.yml
  ansible-ipi-install/roles/node-prep/tasks/100_create-install-config.yml
  ansible-ipi-install/roles/node-prep/tasks/10_validation.yml
  ansible-ipi-install/roles/node-prep/tasks/110_power_off_cluster_servers.yml
  ansible-ipi-install/roles/node-prep/tasks/20_sub_man_register.yml
  ansible-ipi-install/roles/node-prep/tasks/30_req_packages.yml
  ansible-ipi-install/roles/node-prep/tasks/40_bridge.yml
  ansible-ipi-install/roles/node-prep/tasks/50_modify_sudo_user.yml
  ansible-ipi-install/roles/node-prep/tasks/60_enabled_services.yml
  ansible-ipi-install/roles/node-prep/tasks/70_enabled_fw_services.yml
  ansible-ipi-install/roles/node-prep/tasks/80_libvirt_pool.yml
  ansible-ipi-install/roles/node-prep/tasks/90_create_config_install_dirs.yml
  ansible-ipi-install/roles/node-prep/tasks/main.yml
  ansible-ipi-install/roles/node-prep/templates/dir.xml.j2
  ansible-ipi-install/roles/node-prep/templates/install-config.j2
  ansible-ipi-install/roles/node-prep/templates/pub_nic.j2
  ansible-ipi-install/roles/node-prep/tests/inventory
  ansible-ipi-install/roles/node-prep/tests/test.yml
  ansible-ipi-install/roles/node-prep/vars/main.yml
Labels: approved, lgtm, size/XXL

#136 Clear clusterconfig dir during node-prep
  ansible-ipi-install/roles/node-prep/tasks/90_create_config_install_dirs.yml
Labels: lgtm, needs-ok-to-test, size/XS

#142 fixing table of contents, some typos in readme
  ansible-ipi-install/README.md
Labels: size/S

#141 adding myself as code reviewer and approver
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#128 Add step to verify OCP CI release exists in mirror
  install-steps.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#140 Fixing masters,workers hostnames and adding steps for OCP GA install
  install-steps.md
Labels: approved, lgtm, size/M

#149 adding networkType OVNKubernetes as default during installs
  ansible-ipi-install/README.md
  ansible-ipi-install/inventory/hosts.sample
  ansible-ipi-install/roles/node-prep/defaults/main.yml
  ansible-ipi-install/roles/node-prep/templates/install-config.j2
Labels: approved, lgtm, size/XS

#157 adding OVNKubernetes as default network type in install-steps doc
  install-steps.md
Labels: approved, lgtm, size/XS

#146 Feature Enhancements of removing binaries from /usr/loca/bin and cleaning up tmp dirs
  ansible-ipi-install/roles/installer/tasks/10_get_oc.yml
  ansible-ipi-install/roles/installer/tasks/20_extract_installer.yml
Labels: approved, lgtm, size/M, tide/merge-method-squash

#138 Clear bootstrap resources with Ansible
  ansible-ipi-install/README.md
  ansible-ipi-install/roles/installer/tasks/59_cleanup_bootstrap.yml
  ansible-ipi-install/roles/installer/tasks/main.yml
  ansible-ipi-install/roles/installer/vars/main.yml
  install-steps.md
Labels: approved, lgtm, needs-ok-to-test, size/M

#154 Inject prov_nic into install-config
  ansible-ipi-install/roles/node-prep/templates/install-config.j2
Labels: approved, lgtm, ok-to-test, size/XS

#162 Add ability to specify the apivip and ingressvip in inventory/hosts
  ansible-ipi-install/README.md
  ansible-ipi-install/inventory/hosts.sample
  ansible-ipi-install/roles/node-prep/tasks/10_validation.yml
Labels: approved, lgtm, ok-to-test, size/S

#164 Fix install-config prov intf inject logic
  ansible-ipi-install/roles/node-prep/templates/install-config.j2
Labels: approved, lgtm, ok-to-test, size/XS

#163 reflecting the use of ansible playbooks over baremetal-prep. fixes #155
  README.md
Labels: approved, lgtm, size/XS

#161 Do not generate metal3-config for 4.4+
  ansible-ipi-install/roles/installer/tasks/40_create_manifest.yml
  ansible-ipi-install/roles/installer/tasks/main.yml
Labels: approved, lgtm, ok-to-test, size/XS

#139 Shared labs
  ansible-ipi-install/README.md
  ansible-ipi-install/roles/installer/files/customize_filesystem/master/.gitkeep
  ansible-ipi-install/roles/installer/files/customize_filesystem/worker
  ansible-ipi-install/roles/installer/files/manifests/.gitkeep
  ansible-ipi-install/roles/installer/tasks/20_extract_installer.yml
  ansible-ipi-install/roles/installer/tasks/25_customize_filesystem.yml
  ansible-ipi-install/roles/installer/tasks/50_extramanifests.yml
  ansible-ipi-install/roles/installer/tasks/60_deploy_ocp.yml
  ansible-ipi-install/roles/installer/tasks/main.yml
  ansible-ipi-install/roles/node-prep/defaults/main.yml
  ansible-ipi-install/roles/node-prep/tasks/10_validation.yml
  ansible-ipi-install/roles/node-prep/tasks/40_bridge.yml
  ansible-ipi-install/roles/node-prep/tasks/60_enabled_services.yml
  ansible-ipi-install/roles/node-prep/tasks/70_enabled_fw_services.yml
  ansible-ipi-install/roles/node-prep/vars/main.yml
Labels: approved, lgtm, ok-to-test, size/L

#166 Add support for hardwareprofile
  ansible-ipi-install/README.md
  ansible-ipi-install/inventory/hosts.sample
  ansible-ipi-install/roles/node-prep/templates/install-config.j2
Labels: approved, lgtm, size/S

#168 Check for hardware_profile in host vars
  ansible-ipi-install/roles/node-prep/templates/install-config.j2
Labels: approved, lgtm, needs-ok-to-test, size/S

#173 Add the ability to customize the bootstrap image
  ansible-ipi-install/README.md
  ansible-ipi-install/inventory/hosts.sample
  ansible-ipi-install/roles/node-prep/templates/install-config.j2
Labels: approved, lgtm, size/S

#175 adding the clusterosimage feature
  ansible-ipi-install/README.md
  ansible-ipi-install/inventory/hosts.sample
  ansible-ipi-install/roles/node-prep/templates/install-config.j2
Labels: approved, lgtm, size/S

#152 Add Container-native virtualization feature
  README.md
  features/cnv/01-cnv-namespace.yaml
  features/cnv/02-cnv-operatorgroup.yaml
  features/cnv/03-cnv-subscription.yaml
  features/cnv/04-cnv-hcocr.yaml
  features/cnv/README.md
  features/cnv/deploy.sh
  features/cnv/myvars.example
Labels: approved, lgtm, ok-to-test, size/M

#177 Fix jinja syntax in install-config template
  ansible-ipi-install/roles/node-prep/templates/install-config.j2
Labels: approved, lgtm, ok-to-test, size/XS

#178 fixing some typos, adding some fw dnsmasq, changing start firewalld t…
  install-steps.md
Labels: approved, lgtm, ok-to-test, size/M
