Repository openshift-kni/baremetal-deploy, pull requests merged in 2020-04, with the labels that each got.

#254 Update readme formatting
  ansible-ipi-install/README.md
Labels: approved, lgtm, ok-to-test

#267 restarting firewall for persistent rules, fixes #266
  ansible-ipi-install/roles/node-prep/tasks/70_enabled_fw_services.yml
Labels: approved, lgtm

#268 check to see if using yum package directly fixes not installing certain packages
  ansible-ipi-install/roles/node-prep/tasks/30_req_packages.yml
Labels: approved, lgtm

#269 Adds Pre-commit and yaspeller data to this repository
  .flake8
  .pre-commit-config.yaml
  .yaspeller.json
  CONTRIBUTING.md
Labels: approved, lgtm, ok-to-test

#273 Fix alignment
  ansible-ipi-install/README.md
Labels: approved, lgtm

#272 adding pablo as reviewer
  OWNERS_ALIASES
Labels: approved, lgtm

#276 adding troubleshooting image flow chart
  images/troubleshooting.png
Labels: approved, lgtm

#192 Adding Troubleshooting guide
  troubleshooting.md
Labels: approved, lgtm, ok-to-test, size/XL

#275 Add TOC and some format via pre-commit
  .yaspeller.json
  install-steps.md
Labels: approved, lgtm

#278 Swap order of variables
  install-steps.md
Labels: approved, lgtm

#249 Adding proxy capability to the playbook and adding proxy to OpenShift
  ansible-ipi-install/README.md
  ansible-ipi-install/inventory/hosts.sample
  ansible-ipi-install/playbook.yml
  ansible-ipi-install/roles/installer/templates/install-config.j2
  ansible-ipi-install/roles/node-prep/defaults/main.yml
  ansible-ipi-install/roles/node-prep/tasks/40_bridge.yml
Labels: approved, lgtm

#271 Use two letter country
  ansible-ipi-install/README.md
  ansible-ipi-install/inventory/hosts.sample
Labels: approved, lgtm, ok-to-test

#285 swapping ports to correct publish line
  ansible-ipi-install/roles/installer/tasks/15_disconnected_registry_create.yml
Labels: approved, lgtm

#280 Poweroff only required hosts
  ansible-ipi-install/README.md
  ansible-ipi-install/inventory/hosts.sample
  ansible-ipi-install/roles/node-prep/tasks/100_power_off_cluster_servers.yml
Labels: approved, lgtm

#283 Adding ability to specify custom webserver caching port, fixing bool
  ansible-ipi-install/inventory/hosts.sample
  ansible-ipi-install/roles/installer/defaults/main.yml
  ansible-ipi-install/roles/installer/tasks/24_rhcos_image_cache.yml
  ansible-ipi-install/roles/installer/tasks/main.yml
  ansible-ipi-install/roles/node-prep/tasks/10_validation.yml
  ansible-ipi-install/roles/node-prep/tasks/30_req_packages.yml
  ansible-ipi-install/roles/node-prep/tasks/70_enabled_fw_services.yml
Labels: approved, lgtm

#286 adding new images and fixing doc link
  images/71_OpenShift_Baremetal_IPI_Depoyment_0320_1.png
  images/71_OpenShift_Baremetal_IPI_Depoyment_0320_2.png
  images/OpenShift_Baremetal_IPI_Depoyment_1.png
  images/OpenShift_Baremetal_IPI_Depoyment_2.png
  install-steps.md
Labels: approved, lgtm

#288 fixing isolating regathering network facts via a tag
  ansible-ipi-install/roles/node-prep/tasks/40_bridge.yml
  ansible-ipi-install/roles/node-prep/tasks/main.yml
Labels: approved, lgtm

#298 adding flexibility mix and match ipv4 and ipv6 bridges
  ansible-ipi-install/README.md
  ansible-ipi-install/inventory/hosts.sample
  ansible-ipi-install/roles/node-prep/defaults/main.yml
  ansible-ipi-install/roles/node-prep/tasks/40_bridge.yml
Labels: approved, lgtm

#301 adding correct conditionals to the subnets
  ansible-ipi-install/roles/node-prep/tasks/40_bridge.yml
Labels: approved, lgtm

#303 fixes tag on 40_create_manifest.yml
  ansible-ipi-install/roles/installer/tasks/40_create_manifest.yml
Labels: approved, lgtm

#290 Created new documentation folder and contents for upstream.
  documentation/Makefile
  documentation/common
  documentation/deploying-ipi-bare-metal.adoc
  documentation/docinfo.xml
  documentation/images/71_OpenShift_Baremetal_IPI_Depoyment_0320_1.png
  documentation/images/71_OpenShift_Baremetal_IPI_Depoyment_0320_2.png
  documentation/images/troubleshooting.png
  documentation/ipi-install-prerequisites.adoc
  documentation/ipi-install-troubleshooting.adoc
  documentation/ipi-install-upstream-master.adoc
  documentation/modules/common-attributes.adoc
  documentation/modules/ip-install-upstream-choosing-an-openshift-installer-release-from-ci-development.adoc
  documentation/modules/ipi-install--upstream-deploying-the-provisioner-node-as-a-worker-node-using-metal3.adoc
  documentation/modules/ipi-install-additional-install-config-parameters.adoc
  documentation/modules/ipi-install-configuring-nodes.adoc
  documentation/modules/ipi-install-configuring-the-install-config-file.adoc
  documentation/modules/ipi-install-configuring-the-metal3-config-file.adoc
  documentation/modules/ipi-install-creating-a-disconnected-registry.adoc
  documentation/modules/ipi-install-creating-an-rhcos-images-cache.adoc
  documentation/modules/ipi-install-creating-the-openshift-manifests.adoc
  documentation/modules/ipi-install-deploying-the-cluster-via-the-openshift-installer.adoc
  documentation/modules/ipi-install-extracting-the-openshift-installer.adoc
  documentation/modules/ipi-install-network-requirements.adoc
  documentation/modules/ipi-install-node-requirements.adoc
  documentation/modules/ipi-install-out-of-band-management.adoc
  documentation/modules/ipi-install-preparing-the-provision-node-for-openshift-install.adoc
  documentation/modules/ipi-install-required-data-for-installation.adoc
  documentation/modules/ipi-install-retrieving-the-openshift-installer.adoc
  documentation/modules/ipi-install-troubleshooting-the-bootstrap-vm.adoc
  documentation/modules/ipi-install-troubleshooting-the-control-plane.adoc
  documentation/modules/ipi-install-upstream-appending-dns-records-for-the worker-2-(old provisioner)-on-a-DNS-server-option1.adoc
  documentation/modules/ipi-install-upstream-appending-dns-records-for-the worker-2-(old provisioner)-using-dnsmasq-option2.adoc
  documentation/modules/ipi-install-upstream-backing-up-the-cluster-configuration.adoc
  documentation/modules/ipi-install-upstream-choosing-the-latest-openshift-installer-development.adoc
  documentation/modules/ipi-install-upstream-creating-dhcp-reservations-for-the worker-2-(old provisioner)-on-a-DHCP-server-option1.adoc
  documentation/modules/ipi-install-upstream-creating-dhcp-reservations-for-the worker-2-(old provisioner)-using-dnsmasq-option2.adoc
  documentation/modules/ipi-install-upstream-creating-dhcp-reservations-option1.adoc
  documentation/modules/ipi-install-upstream-creating-dhcp-reservations-using-dnsmasq-option2.adoc
  documentation/modules/ipi-install-upstream-creating-dns-records-on-a-dns-server-option1.adoc
  documentation/modules/ipi-install-upstream-creating-dns-records-using-dnsmasq-option2.adoc
  documentation/modules/ipi-install-upstream-deploying-routers-on-worker-nodes.adoc
  documentation/modules/ipi-install-upstream-deploying-the-provisioner-node-as-a-worker-node-using-metal3.adoc
  documentation/modules/ipi-install-upstream-extracting-the-installer-development.adoc
  documentation/modules/ipi-install-upstream-installing-rhel-on-the-provision-node.adoc
  documentation/modules/ipi-install-upstream-preparing-the-provisioner-node-to-be-deployed-as-a-worker-node.adoc
  documentation/modules/ipi-install-upstream-reserving-ips-for-vips-and-nodes.adoc
  documentation/modules/ipi-install-upstream-retrieving-the-openshift-installer-development.adoc
  documentation/modules/ipi-install-validation-checklist-for-installation.adoc
  documentation/modules/ipi-install-validation-checklist-for-nodes.adoc
Labels: approved, lgtm

#307 Add Travis configuration
  .travis.yml
Labels: approved, lgtm

#308 Change output dir
  .travis.yml
Labels: approved, lgtm

#309 Onbranchmaster
  .travis.yml
Labels: approved, lgtm

#311 Skip cleanup
  .travis.yml
Labels: approved, lgtm

#310 updating documentation for upstream
  documentation/deploying-ipi-bare-metal.adoc
  documentation/ipi-install-prerequisites.adoc
  documentation/ipi-install-upstream-master.adoc
  documentation/modules/ipi-install--upstream-deploying-the-provisioner-node-as-a-worker-node-using-metal3.adoc
  documentation/modules/ipi-install-configuring-the-install-config-file.adoc
  documentation/modules/ipi-install-configuring-the-metal3-config-file.adoc
  documentation/modules/ipi-install-extracting-the-openshift-installer.adoc
  documentation/modules/ipi-install-network-requirements.adoc
  documentation/modules/ipi-install-preparing-the-provision-node-for-openshift-install.adoc
  documentation/modules/ipi-install-retrieving-the-openshift-installer.adoc
  documentation/modules/ipi-install-upstream-backing-up-the-cluster-configuration.adoc
  documentation/modules/ipi-install-upstream-choosing-the-latest-openshift-installer-development.adoc
  documentation/modules/ipi-install-upstream-creating-dhcp-reservations-using-dnsmasq-option2.adoc
  documentation/modules/ipi-install-upstream-deploying-routers-on-worker-nodes.adoc
  documentation/modules/ipi-install-upstream-extracting-the-installer-development.adoc
  documentation/modules/ipi-install-upstream-installing-rhel-on-the-provision-node.adoc
Labels: approved, lgtm

#300 Allow to specify different prov_nic for masters
  ansible-ipi-install/README.md
  ansible-ipi-install/inventory/hosts.sample
  ansible-ipi-install/roles/installer/templates/install-config.j2
  ansible-ipi-install/roles/node-prep/tasks/10_validation.yml
Labels: approved, lgtm, ok-to-test

#312 Update formatting for install-steps.md
  install-steps.md
Labels: approved, lgtm, ok-to-test

#304 Use hostvars[host]['inventory_hostname'] in install-config.j2
  ansible-ipi-install/roles/installer/templates/install-config.j2
Labels: approved, lgtm, ok-to-test

#315 Define reviewers and label for ansible-ipi-install folder
  OWNERS
Labels: approved, lgtm

#314 Netlifybadge
  .yaspeller.json
  CODE_OF_CONDUCT.md
  README.md
Labels: approved, lgtm

#318 Prepare scripted build
  .travis.yml
  Gemfile
  Rakefile
  documentation/ipi-install-upstream-master.adoc
  utils/build.sh
Labels: approved, lgtm

#319 Remove spaces
  ansible-ipi-install/README.md
  ansible-ipi-install/inventory/hosts.sample
  ansible-ipi-install/roles/installer/tasks/10_get_oc.yml
  ansible-ipi-install/roles/installer/tasks/15_disconnected_registry_create.yml
  ansible-ipi-install/roles/installer/tasks/20_extract_installer.yml
  ansible-ipi-install/roles/installer/tasks/23_rhcos_image_paths.yml
  ansible-ipi-install/roles/installer/tasks/25_create-install-config.yml
  ansible-ipi-install/roles/installer/tasks/40_create_manifest.yml
  ansible-ipi-install/roles/installer/tasks/50_extramanifests.yml
  ansible-ipi-install/roles/installer/tasks/60_deploy_ocp.yml
  ansible-ipi-install/roles/installer/tasks/main.yml
  ansible-ipi-install/roles/node-prep/handlers/main.yml
  ansible-ipi-install/roles/node-prep/tasks/100_power_off_cluster_servers.yml
  ansible-ipi-install/roles/node-prep/tasks/15_validation_disconnected_registry.yml
  ansible-ipi-install/roles/node-prep/tasks/20_sub_man_register.yml
  ansible-ipi-install/roles/node-prep/tasks/40_bridge.yml
  ansible-ipi-install/roles/node-prep/tasks/50_modify_sudo_user.yml
  ansible-ipi-install/roles/node-prep/tasks/60_enabled_services.yml
  ansible-ipi-install/roles/node-prep/tasks/80_libvirt_pool.yml
  ansible-ipi-install/roles/node-prep/tasks/90_create_config_install_dirs.yml
  ansible-ipi-install/roles/node-prep/tasks/main.yml
  ansible-ipi-install/roles/node-prep/tests/inventory
  ansible-ipi-install/roles/node-prep/tests/test.yml
Labels: approved, lgtm

#320 Gulp
  .gitignore
  .yaspeller.json
  documentation/README.md
  gulpfile.babel.js
  package.json
Labels: approved, lgtm

#323 Copying customize_filesystem to tempdir; Adding filetranspile as a local script
  ansible-ipi-install/roles/installer/files/filetranspile-1.1.1.py
  ansible-ipi-install/roles/installer/tasks/35_customize_filesystem.yml
Labels: approved, lgtm, ok-to-test

#325 reordering to put creation of ignition configs after creation of manifests
  ansible-ipi-install/roles/installer/tasks/55_customize_filesystem.yml
  ansible-ipi-install/roles/installer/tasks/main.yml
Labels: approved, lgtm, ok-to-test

#306 Do not restart firewalld and use immediate
  ansible-ipi-install/roles/node-prep/tasks/60_enabled_services.yml
  ansible-ipi-install/roles/node-prep/tasks/70_enabled_fw_services.yml
Labels: approved, lgtm

#327 Add remote_src for copying ignition files
  ansible-ipi-install/roles/installer/tasks/55_customize_filesystem.yml
Labels: approved, lgtm, ok-to-test

#330 revert part of #306 change to correct firewall service and port problem when using iptables
  ansible-ipi-install/roles/node-prep/tasks/70_enabled_fw_services.yml
Labels: approved, lgtm, ok-to-test

#328 Install python3-yaml on the provsioner for filetranspile script
  ansible-ipi-install/roles/node-prep/vars/main.yml
Labels: approved, lgtm, ok-to-test

#171 Enable async install and looping of wait-for commands
  ansible-ipi-install/README.md
  ansible-ipi-install/inventory/hosts.sample
  ansible-ipi-install/roles/installer/tasks/60_deploy_ocp.yml
Labels: approved, lgtm, ok-to-test, size/M

#337 Take backup of ignition files used by installer
  ansible-ipi-install/README.md
  ansible-ipi-install/roles/installer/tasks/55_customize_filesystem.yml
Labels: approved, lgtm, ok-to-test

#336 isolating network facts into its own task file
  ansible-ipi-install/README.md
  ansible-ipi-install/roles/node-prep/tasks/40_bridge.yml
  ansible-ipi-install/roles/node-prep/tasks/45_networking_facts.yml
  ansible-ipi-install/roles/node-prep/tasks/main.yml
Labels: approved, lgtm

#321 Documentation reorganization
  .yaspeller.json
  Gemfile
  README.md
  ansible-ipi-install/README.md
  documentation/images/71_OpenShift_Baremetal_IPI_Depoyment_0320_2.png
  documentation/ipi-install-prerequisites.adoc
  documentation/ipi-install-upstream-master.adoc
  documentation/modules/ipi-install--upstream-deploying-the-provisioner-node-as-a-worker-node-using-metal3.adoc
  documentation/modules/ipi-install-config-yaml-4.3.adoc
  documentation/modules/ipi-install-config-yaml.adoc
  documentation/modules/ipi-install-configuration-files.adoc
  documentation/modules/ipi-install-configuring-the-install-config-file.adoc
  documentation/modules/ipi-install-configuring-the-metal3-config-file.adoc
  documentation/modules/ipi-install-creating-a-disconnected-registry.adoc
  documentation/modules/ipi-install-creating-an-rhcos-images-cache.adoc
  documentation/modules/ipi-install-creating-the-openshift-manifests.adoc
  documentation/modules/ipi-install-deploying-the-cluster-via-the-openshift-installer.adoc
  documentation/modules/ipi-install-extracting-the-openshift-installer.adoc
  documentation/modules/ipi-install-network-requirements.adoc
  documentation/modules/ipi-install-preparing-the-provisioner-node-for-openshift-install.adoc
  documentation/modules/ipi-install-retrieving-openshift-installer-GA.adoc
  documentation/modules/ipi-install-retrieving-openshift-installer-UPSTREAM.adoc
  documentation/modules/ipi-install-retrieving-openshift-installer.adoc
  documentation/modules/ipi-install-retrieving-the-openshift-installer.adoc
  documentation/modules/ipi-install-troubleshooting-the-bootstrap-vm.adoc
  documentation/modules/ipi-install-upstream-appending-dns-records-for-the-worker-2-old-provisioner-on-a-DNS-server-option1.adoc
  documentation/modules/ipi-install-upstream-appending-dns-records-for-the-worker-2-old-provisioner-using-dnsmasq-option2.adoc
  documentation/modules/ipi-install-upstream-appendix.adoc
  documentation/modules/ipi-install-upstream-backing-up-the-cluster-configuration.adoc
  documentation/modules/ipi-install-upstream-creating-dhcp-reservations-for-the-worker-2-old-provisioner-on-a-DHCP-server-option1.adoc
  documentation/modules/ipi-install-upstream-creating-dhcp-reservations-for-the-worker-2-old-provisioner-using-dnsmasq-option2.adoc
  documentation/modules/ipi-install-upstream-creating-dhcp-reservations-option1.adoc
  documentation/modules/ipi-install-upstream-creating-dhcp-reservations-using-dnsmasq-option2.adoc
  documentation/modules/ipi-install-upstream-creating-dns-records-on-a-dns-server-option1.adoc
  documentation/modules/ipi-install-upstream-creating-dns-records-using-dnsmasq-option2.adoc
  documentation/modules/ipi-install-upstream-day2.adoc
  documentation/modules/ipi-install-upstream-deploying-routers-on-worker-nodes.adoc
  documentation/modules/ipi-install-upstream-deploying-the-provisioner-node-as-a-worker-node-using-metal3.adoc
  documentation/modules/ipi-install-upstream-dhcp-for-the-worker.adoc
  documentation/modules/ipi-install-upstream-dhcp.adoc
  documentation/modules/ipi-install-upstream-dns-records-for-the-worker.adoc
  documentation/modules/ipi-install-upstream-dns.adoc
  documentation/modules/ipi-install-upstream-extracting-the-installer-development.adoc
  documentation/modules/ipi-install-upstream-retrieving-the-latest-openshift-installer-development.adoc
  documentation/modules/ipi-install-upstream-retrieving-the-openshift-installer-development.adoc
  documentation/modules/ipi-install-upstream-select-an-openshift-installer-release-from-ci-development.adoc
  documentation/modules/ipi-install-validation-checklist-for-installation.adoc
  documentation/modules/ipi-install-validation-checklist-for-nodes.adoc
  images/OpenShift_Baremetal_IPI_Depoyment_1.png
  images/OpenShift_Baremetal_IPI_Depoyment_2.png
  images/troubleshooting.png
  install-steps.md
  troubleshooting.md
  utils/build.sh
Labels: approved, lgtm

#338 [doc] Changes required in the documentation to support IPv6 provisioning
  documentation/modules/ipi-install-nmcli-setup-4.3.adoc
  documentation/modules/ipi-install-nmcli-setup.adoc
  documentation/modules/ipi-install-node-requirements.adoc
  documentation/modules/ipi-install-preparing-the-provisioner-node-for-openshift-install.adoc
Labels: approved, lgtm

#340 Jekyll
  .travis.yml
  .yaspeller.json
  utils/build-jekyll.sh
  utils/build.sh
  website/Gemfile
  website/_config.yml
  website/index.md
Labels: approved, lgtm

#342 [doc] Changing path of where domain.crt is located in provision host
  documentation/modules/ipi-install-creating-a-disconnected-registry.adoc
Labels: approved, lgtm

#344 Added required logic for proper setting IPv6 settings
  ansible-ipi-install/roles/installer/templates/install-config.j2
Labels: approved, lgtm

#346 move backup of ignition configs to inside block
  ansible-ipi-install/roles/installer/tasks/55_customize_filesystem.yml
Labels: approved, lgtm
