Repository openshift-kni/baremetal-deploy, pull requests merged in 2020-01, with the labels that each got.

#121 small changes to the document based on feedback, fixes #114, fixes #1…
  install-steps.md
Labels: lgtm, size/M

#109 feature bonding: added steps for bonding using MCO
  features/bonding/README.md
  features/bonding/examples/mco-bonding.md
Labels: approved, lgtm, ok-to-test, size/L

#123 Provide a more detailed description of how enable sctp and what it is
  features/sctp/README.md
  features/sctp/sctp_module_mc.yaml
Labels: size/M

#124 Performance e2e tests
  features/functests/performance/performance.go
  features/functests/utils/clients/clients.go
  features/go.mod
  features/go.sum
  features/performance/file_to_remove_later
  features/performance/manifests/templates/00-tuned-network-latency.yaml.in
  features/vendor/github.com/ishidawataru/sctp/.gitignore
  features/vendor/github.com/ishidawataru/sctp/.travis.yml
  features/vendor/github.com/ishidawataru/sctp/GO_LICENSE
  features/vendor/github.com/ishidawataru/sctp/LICENSE
  features/vendor/github.com/ishidawataru/sctp/README.md
  features/vendor/github.com/ishidawataru/sctp/ipsock_linux.go
  features/vendor/github.com/ishidawataru/sctp/sctp.go
  features/vendor/github.com/ishidawataru/sctp/sctp_linux.go
  features/vendor/github.com/ishidawataru/sctp/sctp_unsupported.go
  features/vendor/github.com/openshift/cluster-node-tuning-operator/pkg/generated/clientset/versioned/clientset.go
  features/vendor/github.com/openshift/cluster-node-tuning-operator/pkg/generated/clientset/versioned/doc.go
  features/vendor/github.com/openshift/cluster-node-tuning-operator/pkg/generated/clientset/versioned/scheme/doc.go
  features/vendor/github.com/openshift/cluster-node-tuning-operator/pkg/generated/clientset/versioned/scheme/register.go
  features/vendor/github.com/openshift/cluster-node-tuning-operator/pkg/generated/clientset/versioned/typed/tuned/v1/doc.go
  features/vendor/github.com/openshift/cluster-node-tuning-operator/pkg/generated/clientset/versioned/typed/tuned/v1/generated_expansion.go
  features/vendor/github.com/openshift/cluster-node-tuning-operator/pkg/generated/clientset/versioned/typed/tuned/v1/profile.go
  features/vendor/github.com/openshift/cluster-node-tuning-operator/pkg/generated/clientset/versioned/typed/tuned/v1/tuned.go
  features/vendor/github.com/openshift/cluster-node-tuning-operator/pkg/generated/clientset/versioned/typed/tuned/v1/tuned_client.go
  features/vendor/golang.org/x/net/html/atom/gen.go
  features/vendor/golang.org/x/sys/unix/mkasm_darwin.go
  features/vendor/golang.org/x/sys/unix/mkpost.go
  features/vendor/golang.org/x/sys/unix/mksyscall.go
  features/vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  features/vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  features/vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  features/vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  features/vendor/golang.org/x/sys/unix/mksysnum.go
  features/vendor/golang.org/x/sys/unix/types_aix.go
  features/vendor/golang.org/x/sys/unix/types_darwin.go
  features/vendor/golang.org/x/sys/unix/types_dragonfly.go
  features/vendor/golang.org/x/sys/unix/types_freebsd.go
  features/vendor/golang.org/x/sys/unix/types_netbsd.go
  features/vendor/golang.org/x/sys/unix/types_openbsd.go
  features/vendor/golang.org/x/sys/unix/types_solaris.go
  features/vendor/golang.org/x/text/encoding/charmap/maketables.go
  features/vendor/golang.org/x/text/encoding/htmlindex/gen.go
  features/vendor/golang.org/x/text/encoding/internal/identifier/gen.go
  features/vendor/golang.org/x/text/encoding/japanese/maketables.go
  features/vendor/golang.org/x/text/encoding/korean/maketables.go
  features/vendor/golang.org/x/text/encoding/simplifiedchinese/maketables.go
  features/vendor/golang.org/x/text/encoding/traditionalchinese/maketables.go
  features/vendor/golang.org/x/text/internal/language/compact/gen.go
  features/vendor/golang.org/x/text/internal/language/compact/gen_index.go
  features/vendor/golang.org/x/text/internal/language/compact/gen_parents.go
  features/vendor/golang.org/x/text/internal/language/gen.go
  features/vendor/golang.org/x/text/internal/language/gen_common.go
  features/vendor/golang.org/x/text/language/gen.go
  features/vendor/golang.org/x/text/unicode/bidi/gen.go
  features/vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  features/vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  features/vendor/golang.org/x/text/unicode/norm/maketables.go
  features/vendor/golang.org/x/text/unicode/norm/triegen.go
  features/vendor/modules.txt
Labels: approved, lgtm, ok-to-test, size/XXL

#117 Adding PTP functional tests
  features/Makefile
  features/functests/ptp/ptp.go
  features/functests/test_suite_test.go
Labels: approved, lgtm, ok-to-test, size/L

#130 Install golang via gimme
  features/Dockefile.buildimage
Labels: lgtm, size/S
