Repository openshift-kni/baremetal-deploy, pull requests merged in 2020-08, with the labels that each got.

#478 Intelligently decide between using IPMI or RedFish protocol based on Vendor and Firmware version
  ansible-ipi-install/inventory/hosts.sample
  ansible-ipi-install/roles/installer/templates/install-config.j2
  ansible-ipi-install/roles/node-prep/defaults/main.yml
  ansible-ipi-install/roles/node-prep/tasks/10_validation.yml
  documentation/ansible-playbook/modules/ansible-playbook-modifying-the-inventoryhosts-file.adoc
Labels: approved, kind/documentation, lgtm

#480 Update images and text for DNSVIP
  documentation/ipi-install/deploying-ipi-bare-metal.adoc
  documentation/ipi-install/images/4.4-71_OpenShift_Baremetal_IPI_Depoyment_0320_1.png
  documentation/ipi-install/images/4.4-71_OpenShift_Baremetal_IPI_Depoyment_0320_2.png
  documentation/ipi-install/images/4.5-71_OpenShift_Baremetal_IPI_Depoyment_0320_1.png
  documentation/ipi-install/images/4.5-71_OpenShift_Baremetal_IPI_Depoyment_0320_2.png
  documentation/ipi-install/modules/ipi-install-upstream-creating-dhcp-reservations-using-dnsmasq-option2.adoc
Labels: approved, kind/documentation, lgtm

#479 Adding cert verification parameter
  documentation/ipi-install/modules/ipi-install-additional-install-config-parameters.adoc
Labels: approved, kind/documentation, lgtm

#482 Tune stale timeouts and add greetings for new contributors and dependabot
  .github/dependabot.yml
  .github/workflows/greetings.yml
  .github/workflows/stale.yml
Labels: approved, lgtm

#483 Sort versions for docs
  utils/build.sh
Labels: approved, lgtm

#484 Redfish dell
  documentation/ipi-install/modules/ipi-install-additional-install-config-parameters.adoc
Labels: approved, kind/documentation, lgtm

#481 Adding retries to the ipmi power off
  ansible-ipi-install/roles/node-prep/tasks/100_power_off_cluster_servers.yml
Labels: approved, lgtm, ok-to-test

#485 Move from Travis to GHA for pages generation
  .github/workflows/jekyll.yml
  .travis.yml
  utils/patch-travis-for-ghpages.sh
Labels: approved, lgtm

#486 Fix baseurl
  website/_config.yml
Labels: approved, lgtm

#487 Change ink from pygments to rouge
  documentation/ansible-playbook/ansible-playbook-fully-disconnected.adoc
  documentation/ansible-playbook/ansible-playbook-readme.adoc
  documentation/ipi-install/ipi-install-upstream-master.adoc
  documentation/troubleshooting/ipi-install-upstream-troubleshooting.adoc
Labels: approved, kind/documentation, lgtm

#488 Add build script
  build.sh
Labels: approved, lgtm

#489 Add placeholder folder
  website/_data/.placeholder
Labels: approved, lgtm

#490 Check broken links
  .github/workflows/broken-link-check.yml
Labels: approved, lgtm

#491 Add Ansible linting GHA
  .github/workflows/ansible-lint.yml
Labels: approved, lgtm

#492 Remove playbook linting
  .github/workflows/ansible-lint.yml
Labels: approved, lgtm

#495 Fix link in Troubleshooting
  documentation/troubleshooting/ipi-install-upstream-troubleshooting.adoc
Labels: approved, kind/documentation, lgtm

#499 Adding multiple retries and a delay when attempting to gather redfish facts for HPE and Dell servers
  ansible-ipi-install/roles/node-prep/tasks/10_validation.yml
Labels: approved, lgtm

#500 Ignore errors on the add host tasks, if there is an error, defaults to IPMI
  ansible-ipi-install/roles/node-prep/tasks/10_validation.yml
Labels: approved, lgtm

#501 Fixing root device hints, making it a per entry of host in inventory
  ansible-ipi-install/inventory/hosts.sample
  ansible-ipi-install/roles/installer/templates/install-config.j2
  ansible-ipi-install/roles/node-prep/defaults/main.yml
  ansible-ipi-install/roles/node-prep/tasks/10_validation.yml
  documentation/ansible-playbook/modules/ansible-playbook-modifying-the-inventoryhosts-file.adoc
Labels: approved, kind/documentation, lgtm
