Repository openshift-kni/baremetal-deploy, pull requests merged in 2020-09, with the labels that each got.

#503 Debug message to mention install log location
  ansible-ipi-install/roles/installer/tasks/60_deploy_ocp.yml
Labels: approved, lgtm

#504 Add retries to task that gets chassis results
  ansible-ipi-install/roles/node-prep/tasks/10_validation.yml
Labels: approved, lgtm, ok-to-test

#511 Adding the ability to turn off firmware and chassis inspection
  ansible-ipi-install/inventory/hosts.sample
  ansible-ipi-install/roles/node-prep/defaults/main.yml
  ansible-ipi-install/roles/node-prep/tasks/10_validation.yml
  documentation/ansible-playbook/modules/ansible-playbook-modifying-the-inventoryhosts-file.adoc
Labels: approved, kind/documentation, lgtm

#513 Fixing GPG key failure errors when attempting to install required pac…
  ansible-ipi-install/roles/node-prep/tasks/30_req_packages.yml
Labels: approved, lgtm

#514 Fixing pull secret location so it matches dir variable
  ansible-ipi-install/roles/installer/vars/main.yml
Labels: approved, lgtm

#515 Specify filename to use for storing download
  documentation/ipi-install/modules/ipi-install-creating-an-rhcos-images-cache.adoc
Labels: approved, kind/documentation, lgtm

#516 Use triple quotes
  documentation/ipi-install/modules/ipi-install-nmcli-setup-4.3.adoc
  documentation/ipi-install/modules/ipi-install-nmcli-setup.adoc
Labels: approved, kind/documentation, lgtm
