Repository openshift-kni/baremetal-deploy, pull requests merged in 2020-05, with the labels that each got.

#352 Fix for masters_nic in 4.3
  ansible-ipi-install/roles/installer/templates/metal3-config.j2
Labels: approved, kind/bug, lgtm

#350 Document how website works
  .gitignore
  .travis.yml
  .yaspeller.json
  Gemfile
  Rakefile
  documentation/README.md
  gulpfile.babel.js
  utils/build-jekyll.sh
  utils/build.sh
  website/Gemfile
  website/_config.yml
  website/_layouts/default.html
  website/_layouts/post.html
  website/_sass/fonts.scss
  website/_sass/jekyll-theme-minimal.scss
  website/_sass/premonition.scss
  website/_sass/rouge-github.scss
  website/assets/css/style.scss
  website/assets/fonts/Noto-Sans-700/Noto-Sans-700.eot
  website/assets/fonts/Noto-Sans-700/Noto-Sans-700.svg
  website/assets/fonts/Noto-Sans-700/Noto-Sans-700.ttf
  website/assets/fonts/Noto-Sans-700/Noto-Sans-700.woff
  website/assets/fonts/Noto-Sans-700/Noto-Sans-700.woff2
  website/assets/fonts/Noto-Sans-700italic/Noto-Sans-700italic.eot
  website/assets/fonts/Noto-Sans-700italic/Noto-Sans-700italic.svg
  website/assets/fonts/Noto-Sans-700italic/Noto-Sans-700italic.ttf
  website/assets/fonts/Noto-Sans-700italic/Noto-Sans-700italic.woff
  website/assets/fonts/Noto-Sans-700italic/Noto-Sans-700italic.woff2
  website/assets/fonts/Noto-Sans-italic/Noto-Sans-italic.eot
  website/assets/fonts/Noto-Sans-italic/Noto-Sans-italic.svg
  website/assets/fonts/Noto-Sans-italic/Noto-Sans-italic.ttf
  website/assets/fonts/Noto-Sans-italic/Noto-Sans-italic.woff
  website/assets/fonts/Noto-Sans-italic/Noto-Sans-italic.woff2
  website/assets/fonts/Noto-Sans-regular/Noto-Sans-regular.eot
  website/assets/fonts/Noto-Sans-regular/Noto-Sans-regular.svg
  website/assets/fonts/Noto-Sans-regular/Noto-Sans-regular.ttf
  website/assets/fonts/Noto-Sans-regular/Noto-Sans-regular.woff
  website/assets/fonts/Noto-Sans-regular/Noto-Sans-regular.woff2
  website/assets/img/logo.png
  website/assets/js/scale.fix.js
  website/index.md
Labels: approved, lgtm

#353 Use Jekyll 4.0
  .travis.yml
  website/Gemfile
Labels: approved, lgtm

#354 Try to fix GP Pages generation
  utils/build-jekyll.sh
Labels: approved, lgtm

#355 Move CSS to assets
  website/_sass/jekyll-theme-minimal.scss
  website/assets/css/style.scss
Labels: approved, lgtm

#356 Fix URLS for GH Pages hosting
  website/_config.yml
Labels: approved, lgtm

#357 Apply GH only settings via .travis
  .travis.yml
  utils/patch-travis-for-ghpages.sh
  website/_config.yml
Labels: approved, lgtm

#359 Use Release of doc for example of nightly
  documentation/modules/ipi-install-upstream-select-an-openshift-installer-release-from-ci-development.adoc
Labels: approved, lgtm

#360 Fix gulp development to point to new paths and create fake index.html
  gulpfile.babel.js
  utils/build-gulp.sh
Labels: approved, lgtm

#361 [doc] Fixing details within the required data section and updating the checklist
  documentation/modules/ipi-install-required-data-for-installation.adoc
  documentation/modules/ipi-install-validation-checklist-for-nodes.adoc
Labels: approved, lgtm

#362 Attempt to tune prow
  OWNERS
  OWNERS_ALIASES
Labels: approved, lgtm

#363 Start building 4.5 docs for testing
  utils/build.sh
Labels: approved, lgtm

#364 Attempt to add keywords
  .yaspeller.json
  website/_config.yml
  website/_includes/metas-ogp.html
  website/_layouts/default.html
  website/index.md
Labels: approved, lgtm

#347 Make workers group in inventory optional
  ansible-ipi-install/README.md
  ansible-ipi-install/roles/installer/templates/install-config.j2
  ansible-ipi-install/roles/node-prep/tasks/100_power_off_cluster_servers.yml
  ansible-ipi-install/roles/node-prep/tasks/10_validation.yml
Labels: approved, lgtm

#367 making some small changes to the README, hosts.sample
  ansible-ipi-install/README.md
  ansible-ipi-install/inventory/hosts.sample
Labels: approved, lgtm

#369 Prepare website and generation scripts to have different sections
  .yaspeller.json
  documentation/Deployment.adoc
  documentation/README.md
  documentation/ipi-install-upstream-master.adoc
  utils/build-gulp.sh
  utils/build.sh
  website/index.md
Labels: approved, kind/documentation, lgtm

#365 Add troubleshooting guide
  documentation/Troubleshooting.adoc
  documentation/ipi-install-upstream-troubleshooting.adoc
  documentation/modules/ipi-install-troubleshooting-api-not-accessible.adoc
  documentation/modules/ipi-install-troubleshooting-bootstrap-vm-cannot-boot.adoc
  documentation/modules/ipi-install-troubleshooting-bootstrap-vm-inspecting-logs.adoc
  documentation/modules/ipi-install-troubleshooting-bootstrap-vm.adoc
  documentation/modules/ipi-install-troubleshooting-cleaning-up-previous-installations.adoc
  documentation/modules/ipi-install-troubleshooting-cluster-nodes-wont-pxe.adoc
  documentation/modules/ipi-install-troubleshooting-flow.adoc
  documentation/modules/ipi-install-troubleshooting-following-the-installation.adoc
  documentation/modules/ipi-install-troubleshooting-install-config.adoc
  documentation/modules/ipi-install-troubleshooting-misc-issues.adoc
  documentation/modules/ipi-install-troubleshooting-ntp-out-of-sync.adoc
  documentation/modules/ipi-install-troubleshooting-post-install-pod-errors.adoc
  documentation/modules/ipi-install-troubleshooting-registry-issues.adoc
  documentation/modules/ipi-install-troubleshooting-review-install.adoc
  troubleshooting.md
  utils/build.sh
Labels: approved, kind/documentation, lgtm

#366 Fully disconnected ansible playbook documentation
  documentation/Ansible-Playbook.adoc
  documentation/ansible-playbook-fully-disconnected.adoc
  documentation/modules/ansible-playbook-docs/ansible-playbook-checklist.adoc
  documentation/modules/ansible-playbook-docs/ansible-playbook-contents-of-the-webserver.adoc
  documentation/modules/ansible-playbook-docs/ansible-playbook-introduction.adoc
  documentation/modules/ansible-playbook-docs/ansible-playbook-modifying-the-inventoryhosts-file-for-fully-disconnected-deployments.adoc
  documentation/modules/ansible-playbook-docs/ansible-playbook-prerequisites.adoc
  documentation/modules/ansible-playbook-docs/ansible-playbook-using-an-existing-registry.adoc
  utils/build.sh
Labels: approved, kind/documentation, lgtm

#370 IPv6 in troubleshooting
  documentation/modules/ipi-install-troubleshooting-misc-issues.adoc
Labels: approved, kind/documentation, lgtm

#368 Adding some recommended changes to the node requirement section
  documentation/modules/ipi-install-node-requirements.adoc
Labels: approved, kind/documentation, lgtm

#339 add parameter for provisioning bridge name
  ansible-ipi-install/README.md
  ansible-ipi-install/inventory/hosts.sample
  ansible-ipi-install/roles/installer/tasks/24_rhcos_image_cache.yml
  ansible-ipi-install/roles/installer/templates/install-config.j2
  ansible-ipi-install/roles/node-prep/defaults/main.yml
  ansible-ipi-install/roles/node-prep/tasks/40_bridge.yml
  ansible-ipi-install/roles/node-prep/tasks/45_networking_facts.yml
Labels: approved, lgtm

#262 adding pieces needed for fully disconnected
  ansible-ipi-install/inventory/hosts.sample
  ansible-ipi-install/roles/installer/defaults/main.yml
  ansible-ipi-install/roles/installer/tasks/10_get_oc.yml
  ansible-ipi-install/roles/installer/tasks/15_disconnected_registry_create.yml
  ansible-ipi-install/roles/installer/tasks/20_extract_installer.yml
  ansible-ipi-install/roles/installer/tasks/23_rhcos_image_paths.yml
  ansible-ipi-install/roles/installer/tasks/24_rhcos_image_cache.yml
  ansible-ipi-install/roles/installer/tasks/main.yml
  ansible-ipi-install/roles/installer/templates/install-config-appends.j2
  ansible-ipi-install/roles/installer/templates/install-config.j2
  ansible-ipi-install/roles/installer/vars/main.yml
  ansible-ipi-install/roles/node-prep/defaults/main.yml
  ansible-ipi-install/roles/node-prep/tasks/10_validation.yml
  ansible-ipi-install/roles/node-prep/tasks/15_validation_disconnected_registry.yml
  ansible-ipi-install/roles/node-prep/tasks/main.yml
  ansible-ipi-install/roles/node-prep/vars/main.yml
Labels: approved, lgtm

#378 Restore owners for ^features
  OWNERS
  OWNERS_ALIASES
Labels: approved, lgtm

#376 Adding logic on how to handle ipmi power required packages
  ansible-ipi-install/README.md
  ansible-ipi-install/roles/node-prep/tasks/10_validation.yml
  ansible-ipi-install/roles/node-prep/vars/main.yml
Labels: approved, lgtm

#371 Use pre-commit on installer
  ansible-ipi-install/README.md
  ansible-ipi-install/inventory/hosts.sample
  ansible-ipi-install/roles/installer/files/filetranspile-1.1.1.py
  ansible-ipi-install/roles/installer/handlers/main.yml
  ansible-ipi-install/roles/installer/library/podman_container.py
  ansible-ipi-install/roles/installer/meta/main.yml
  ansible-ipi-install/roles/installer/tasks/10_get_oc.yml
  ansible-ipi-install/roles/installer/tasks/15_disconnected_registry_create.yml
  ansible-ipi-install/roles/installer/tasks/15_disconnected_registry_existing.yml
  ansible-ipi-install/roles/installer/tasks/20_extract_installer.yml
  ansible-ipi-install/roles/installer/tasks/24_rhcos_image_cache.yml
  ansible-ipi-install/roles/installer/tasks/70_cleanup_sub_man_registeration.yml
  ansible-ipi-install/roles/installer/tasks/main.yml
  ansible-ipi-install/roles/installer/templates/metal3-config.j2
  ansible-ipi-install/roles/installer/tests/inventory
  ansible-ipi-install/roles/installer/tests/test.yml
  ansible-ipi-install/roles/node-prep/library/nmcli.py
  ansible-ipi-install/roles/node-prep/tasks/10_validation.yml
  ansible-ipi-install/roles/node-prep/tasks/main.yml
Labels: approved, lgtm

#380 Restore modules location to ipi-install
  documentation/ipi-install/modules/ipi-install-troubleshooting-the-bootstrap-vm.adoc
  documentation/ipi-install/modules/ipi-install-troubleshooting-the-control-plane.adoc
Labels: approved, kind/documentation, lgtm

#373 Apply pre-commit on remaining folders
  baremetal-prep/README.md
  baremetal-prep/baremetal-prep.sh
  hacks/build-baremetal-installer.md
Labels: approved, lgtm

#379 Add Owners in folders as per PR64
  OWNERS
  OWNERS_ALIASES
  ansible-ipi-install/OWNERS
  documentation/OWNERS
Labels: approved, kind/documentation, lgtm

#382 Use fail for checking ansible version
  ansible-ipi-install/roles/node-prep/tasks/10_validation.yml
Labels: approved, kind/bug, lgtm

#383 Check for required python libraries for creating registry
  ansible-ipi-install/roles/node-prep/tasks/10_validation.yml
Labels: approved, kind/bug, lgtm

#377 Fixing the prerequisites section
  documentation/ansible-playbook/ansible-playbook-fully-disconnected.adoc
  documentation/ansible-playbook/modules/ansible-playbook-ansible-version.adoc
  documentation/ansible-playbook/modules/ansible-playbook-ansiblecfg-file.adoc
  documentation/ansible-playbook/modules/ansible-playbook-appendix-creating-local-repository.adoc
  documentation/ansible-playbook/modules/ansible-playbook-appendix-env-vars-sh.adoc
  documentation/ansible-playbook/modules/ansible-playbook-appendix-helper-script-sh.adoc
  documentation/ansible-playbook/modules/ansible-playbook-appendix-python3-crypto-pyghmi.adoc
  documentation/ansible-playbook/modules/ansible-playbook-checklist.adoc
  documentation/ansible-playbook/modules/ansible-playbook-contents-of-the-webserver.adoc
  documentation/ansible-playbook/modules/ansible-playbook-git-clone.adoc
  documentation/ansible-playbook/modules/ansible-playbook-modifying-the-inventoryhosts-file-for-fully-disconnected-deployments.adoc
  documentation/ansible-playbook/modules/ansible-playbook-prerequisites.adoc
  documentation/ansible-playbook/modules/ansible-playbook-running-the-playbook.adoc
  documentation/ansible-playbook/modules/ansible-playbook-ssh-key.adoc
  documentation/ansible-playbook/modules/ansible-playbook-the-ansible-playbook.adoc
  documentation/ansible-playbook/modules/ansible-playbook-using-an-existing-registry.adoc
Labels: approved, kind/documentation, lgtm

#384 Converting Ansible playbook README.md to HTML and PDF format
  documentation/Ansible-Playbook-Disconnected-Install.adoc
  documentation/Ansible-Playbook-Install.adoc
  documentation/ansible-playbook/ansible-playbook-fully-disconnected.adoc
  documentation/ansible-playbook/ansible-playbook-readme.adoc
  documentation/ansible-playbook/modules/ansible-playbook-adding-extra-configurations-to-the-openshift-installer.adoc
  documentation/ansible-playbook/modules/ansible-playbook-ansible-version.adoc
  documentation/ansible-playbook/modules/ansible-playbook-appendix-using-a-proxy-with-your-ansible-playbook.adoc
  documentation/ansible-playbook/modules/ansible-playbook-appendix-using-ansible-tags-with-the-playbookyml.adoc
  documentation/ansible-playbook/modules/ansible-playbook-contents-of-the-webserver.adoc
  documentation/ansible-playbook/modules/ansible-playbook-creating-a-new-disconnected-registry.adoc
  documentation/ansible-playbook/modules/ansible-playbook-customizing-the-node-filesystems.adoc
  documentation/ansible-playbook/modules/ansible-playbook-dig-lookup-requires-the-python-dnspython-library.adoc
  documentation/ansible-playbook/modules/ansible-playbook-disconnected-introduction.adoc
  documentation/ansible-playbook/modules/ansible-playbook-disconnected-registry.adoc
  documentation/ansible-playbook/modules/ansible-playbook-disconnected-running-the-playbook.adoc
  documentation/ansible-playbook/modules/ansible-playbook-failed-to-install-python3-crypto-python3-pyghmi.adoc
  documentation/ansible-playbook/modules/ansible-playbook-gotchas.adoc
  documentation/ansible-playbook/modules/ansible-playbook-introduction.adoc
  documentation/ansible-playbook/modules/ansible-playbook-missing-python-netaddr-library.adoc
  documentation/ansible-playbook/modules/ansible-playbook-modifying-the-inventoryhosts-file-for-fully-disconnected-deployments.adoc
  documentation/ansible-playbook/modules/ansible-playbook-modifying-the-inventoryhosts-file.adoc
  documentation/ansible-playbook/modules/ansible-playbook-permission-denied-trying-to-connect-to-host.adoc
  documentation/ansible-playbook/modules/ansible-playbook-precaching-rhcos-images.adoc
  documentation/ansible-playbook/modules/ansible-playbook-prerequisites.adoc
  documentation/ansible-playbook/modules/ansible-playbook-running-the-ansible-playbook.adoc
  documentation/ansible-playbook/modules/ansible-playbook-shared-connection-closed-on-provision-host.adoc
  documentation/ansible-playbook/modules/ansible-playbook-tour-of-the-ansible-playbook.adoc
  documentation/ansible-playbook/modules/ansible-playbook-troubleshooting.adoc
  documentation/ansible-playbook/modules/ansible-playbook-unreachable-host.adoc
  documentation/ansible-playbook/modules/ansible-playbook-using-an-existing-registry.adoc
  documentation/ansible-playbook/modules/ansible-playbook-using-become-yes-within-ansiblecfg-or-inside-playbookyml.adoc
  documentation/ansible-playbook/modules/ansible-playbook-verifying-installation.adoc
  utils/build.sh
Labels: approved, kind/documentation, lgtm

#385 Point to new document instead of old README
  ansible-ipi-install/README.md
Labels: approved, lgtm

#386 Allow spaces in filename
  ansible-ipi-install/README.md
  documentation/Ansible Playbook Disconnected Install.adoc
  documentation/Ansible Playbook Install.adoc
  documentation/ansible-playbook/ansible-playbook-fully-disconnected.adoc
  documentation/ansible-playbook/ansible-playbook-readme.adoc
  documentation/ansible-playbook/modules/ansible-playbook-adding-extra-configurations-to-the-openshift-installer.adoc
  documentation/ansible-playbook/modules/ansible-playbook-ansible-version.adoc
  documentation/ansible-playbook/modules/ansible-playbook-ansiblecfg-file.adoc
  documentation/ansible-playbook/modules/ansible-playbook-appendix-creating-local-repository.adoc
  documentation/ansible-playbook/modules/ansible-playbook-appendix-env-vars-sh.adoc
  documentation/ansible-playbook/modules/ansible-playbook-appendix-helper-script-sh.adoc
  documentation/ansible-playbook/modules/ansible-playbook-appendix-python3-crypto-pyghmi.adoc
  documentation/ansible-playbook/modules/ansible-playbook-checklist.adoc
  documentation/ansible-playbook/modules/ansible-playbook-contents-of-the-webserver.adoc
  documentation/ansible-playbook/modules/ansible-playbook-creating-a-new-disconnected-registry.adoc
  documentation/ansible-playbook/modules/ansible-playbook-customizing-the-node-filesystems.adoc
  documentation/ansible-playbook/modules/ansible-playbook-dig-lookup-requires-the-python-dnspython-library.adoc
  documentation/ansible-playbook/modules/ansible-playbook-disconnected-registry.adoc
  documentation/ansible-playbook/modules/ansible-playbook-failed-to-install-python3-crypto-python3-pyghmi.adoc
  documentation/ansible-playbook/modules/ansible-playbook-git-clone.adoc
  documentation/ansible-playbook/modules/ansible-playbook-introduction.adoc
  documentation/ansible-playbook/modules/ansible-playbook-missing-python-netaddr-library.adoc
  documentation/ansible-playbook/modules/ansible-playbook-modifying-the-inventoryhosts-file-for-fully-disconnected-deployments.adoc
  documentation/ansible-playbook/modules/ansible-playbook-modifying-the-inventoryhosts-file.adoc
  documentation/ansible-playbook/modules/ansible-playbook-permission-denied-trying-to-connect-to-host.adoc
  documentation/ansible-playbook/modules/ansible-playbook-precaching-rhcos-images.adoc
  documentation/ansible-playbook/modules/ansible-playbook-shared-connection-closed-on-provision-host.adoc
  documentation/ansible-playbook/modules/ansible-playbook-ssh-key.adoc
  documentation/ansible-playbook/modules/ansible-playbook-the-ansible-playbook.adoc
  documentation/ansible-playbook/modules/ansible-playbook-troubleshooting.adoc
  documentation/ansible-playbook/modules/ansible-playbook-unreachable-host.adoc
  documentation/ansible-playbook/modules/ansible-playbook-using-an-existing-registry.adoc
  documentation/ansible-playbook/modules/ansible-playbook-using-become-yes-within-ansiblecfg-or-inside-playbookyml.adoc
  documentation/ansible-playbook/modules/ansible-playbook-verifying-installation.adoc
  documentation/docinfo.xml
  utils/build.sh
Labels: approved, kind/documentation, lgtm

#389 Move docs to dev preview
  .yaspeller.json
  documentation/ansible-playbook/ansible-playbook-fully-disconnected.adoc
  documentation/ansible-playbook/ansible-playbook-readme.adoc
  documentation/ansible-playbook/images/watermark.png
  documentation/ipi-install/images/watermark.png
  documentation/ipi-install/ipi-install-upstream-master.adoc
  documentation/troubleshooting/images/watermark.png
  documentation/troubleshooting/ipi-install-upstream-troubleshooting.adoc
  utils/build.sh
  website/_config.yml
  website/index.md
Labels: approved, kind/documentation, lgtm

#390 Updating troubleshooting docs
  documentation/troubleshooting/images/flow1.png
  documentation/troubleshooting/images/flow2.png
  documentation/troubleshooting/images/flow3.png
  documentation/troubleshooting/images/flow4.png
  documentation/troubleshooting/modules/ipi-install-troubleshooting-api-not-accessible.adoc
  documentation/troubleshooting/modules/ipi-install-troubleshooting-bootstrap-vm-cannot-boot.adoc
  documentation/troubleshooting/modules/ipi-install-troubleshooting-bootstrap-vm-inspecting-logs.adoc
  documentation/troubleshooting/modules/ipi-install-troubleshooting-bootstrap-vm.adoc
  documentation/troubleshooting/modules/ipi-install-troubleshooting-cleaning-up-previous-installations.adoc
  documentation/troubleshooting/modules/ipi-install-troubleshooting-cluster-nodes-wont-pxe.adoc
  documentation/troubleshooting/modules/ipi-install-troubleshooting-flow.adoc
  documentation/troubleshooting/modules/ipi-install-troubleshooting-following-the-installation.adoc
  documentation/troubleshooting/modules/ipi-install-troubleshooting-install-config.adoc
  documentation/troubleshooting/modules/ipi-install-troubleshooting-misc-issues.adoc
  documentation/troubleshooting/modules/ipi-install-troubleshooting-ntp-out-of-sync.adoc
  documentation/troubleshooting/modules/ipi-install-troubleshooting-post-install-pod-errors.adoc
  documentation/troubleshooting/modules/ipi-install-troubleshooting-registry-issues.adoc
  documentation/troubleshooting/modules/ipi-install-troubleshooting-review-install.adoc
Labels: approved, kind/documentation, lgtm

#392 Fix incorrect URL for openshift-client archive
  documentation/ipi-install/modules/ipi-install-extracting-the-openshift-installer.adoc
Labels: approved, kind/documentation, lgtm

#393 Update document to include copying openshift-baremetall-install to /usr/local/bin
  documentation/ipi-install/modules/ipi-install-extracting-the-openshift-installer.adoc
Labels: approved, kind/documentation, lgtm

#394 Fixing API VIP and Ingress VIP verifications
  ansible-ipi-install/roles/node-prep/tasks/10_validation.yml
  ansible-ipi-install/roles/node-prep/vars/main.yml
Labels: approved, lgtm

#395 Fixing link
  troubleshooting.md
Labels: approved, lgtm

#399 API/Ingress VIP required logic fix on qtype variable
  ansible-ipi-install/roles/node-prep/vars/main.yml
Labels: approved, lgtm

#388 Adding the ability to modify the externalBridge name
  ansible-ipi-install/inventory/hosts.sample
  ansible-ipi-install/roles/installer/templates/install-config.j2
  ansible-ipi-install/roles/node-prep/defaults/main.yml
  ansible-ipi-install/roles/node-prep/tasks/40_bridge.yml
  documentation/ansible-playbook/modules/ansible-playbook-modifying-the-inventoryhosts-file.adoc
Labels: approved, kind/documentation, lgtm

#398 Update docs to suggest some additional package installs
  documentation/ipi-install/modules/ipi-install-creating-an-rhcos-images-cache.adoc
  documentation/ipi-install/modules/ipi-install-preparing-the-provisioner-node-for-openshift-install.adoc
Labels: approved, kind/documentation, lgtm

#397 Clean up nmcli scripts
  documentation/ipi-install/modules/ipi-install-nmcli-setup.adoc
Labels: approved, kind/documentation, lgtm

#408 Fix broken link within the Creating an RHCOS Images section
  documentation/ansible-playbook/modules/ansible-playbook-contents-of-the-webserver.adoc
Labels: approved, kind/documentation, lgtm

#411 Add gulp generator support for docs with spaces
  utils/build-gulp.sh
Labels: approved, lgtm

#412 Remove extra trailing spaces
  documentation/troubleshooting/modules/ipi-install-troubleshooting-api-not-accessible.adoc
  documentation/troubleshooting/modules/ipi-install-troubleshooting-bootstrap-vm-cannot-boot.adoc
  documentation/troubleshooting/modules/ipi-install-troubleshooting-bootstrap-vm-inspecting-logs.adoc
  documentation/troubleshooting/modules/ipi-install-troubleshooting-bootstrap-vm.adoc
  documentation/troubleshooting/modules/ipi-install-troubleshooting-flow.adoc
  documentation/troubleshooting/modules/ipi-install-troubleshooting-misc-issues.adoc
  documentation/troubleshooting/modules/ipi-install-troubleshooting-ntp-out-of-sync.adoc
  documentation/troubleshooting/modules/ipi-install-troubleshooting-registry-issues.adoc
  documentation/troubleshooting/modules/ipi-install-troubleshooting-review-install.adoc
  utils/build-gulp.sh
  utils/build.sh
Labels: approved, kind/documentation, lgtm

#414 Small errors in the documentation that required fixing
  documentation/ansible-playbook/modules/ansible-playbook-appendix-env-vars-sh.adoc
  documentation/ansible-playbook/modules/ansible-playbook-appendix-helper-script-sh.adoc
  documentation/ansible-playbook/modules/ansible-playbook-using-an-existing-registry.adoc
  documentation/ipi-install/modules/ipi-install-creating-a-disconnected-registry.adoc
Labels: approved, kind/documentation, lgtm

#409 Providing better breakdown of options of IPv4 or IPv6 for provisioning network
  documentation/ipi-install/modules/ipi-install-nmcli-setup-4.3.adoc
  documentation/ipi-install/modules/ipi-install-nmcli-setup.adoc
Labels: approved, kind/documentation, lgtm

#415 Added IPv6 doc modules
  documentation/ipi-install/modules/ipi-ipv6-install-config-yaml-4.5.adoc
  documentation/ipi-install/modules/ipi-ipv6-install-network-requirements.adoc
  documentation/ipi-install/modules/ipi-ipv6-install-upstream-creating-dhcp-reservations-using-dnsmasq.adoc
  documentation/troubleshooting/modules/ipi-install-troubleshooting-failed-ignition-during-firstboot.adoc
  documentation/troubleshooting/modules/ipi-install-troubleshooting-servers-not-getting-ipv6-from-dhcp.adoc
Labels: approved, kind/documentation, lgtm

#421 Use headers in gulp index and add DEVPREV docs
  utils/build-gulp.sh
Labels: approved, kind/feature, lgtm

#413 Lower down manifest number
  ansible-ipi-install/roles/installer/tasks/40_create_manifest.yml
  ansible-ipi-install/roles/installer/tasks/50_extramanifests.yml
  ansible-ipi-install/roles/installer/templates/etc-chrony.conf.j2
Labels: approved, kind/bug, lgtm
