Repository openshift-kni/baremetal-deploy, pull requests merged in 2021-02, with the labels that each got.

#647 sudo iranzo
  OWNERS
  OWNERS_ALIASES
Labels: approved, lgtm

#648 Edits from Ashley.
  documentation/ipi-install/ipi-install-expanding-the-cluster.adoc
  documentation/ipi-install/modules/ipi-install-additional-install-config-parameters.adoc
  documentation/ipi-install/modules/ipi-install-configuration-files.adoc
  documentation/ipi-install/modules/ipi-install-network-requirements.adoc
  documentation/ipi-install/modules/ipi-install-preparing-the-bare-metal-node.adoc
Labels: approved, kind/documentation, lgtm

#649 docs(README.md): removes versioning that was obsolete and not reflect…
  README.md
Labels: approved, lgtm

#655 Secure boot is two words.
  documentation/ipi-install/modules/ipi-install-configuring-nodes.adoc
Labels: approved, lgtm

#657 Telcodocs 108
  documentation/ipi-install/modules/ipi-install-bmc-addressing.adoc
  documentation/ipi-install/modules/ipi-install-firmware-requirements-for-installing-with-virtual-media.adoc
Labels: approved, kind/documentation, lgtm

#659 Synchronizes some edits between upstream and downstream.
  documentation/ipi-install/ipi-install-prerequisites.adoc
  documentation/ipi-install/modules/ipi-install-bmc-addressing.adoc
  documentation/ipi-install/modules/ipi-install-creating-a-disconnected-registry.adoc
  documentation/ipi-install/modules/ipi-install-firmware-requirements-for-installing-with-virtual-media.adoc
Labels: approved, kind/documentation, lgtm

#658 Restored the opening comment.
  documentation/ipi-install/modules/ipi-install-creating-a-disconnected-registry.adoc
Labels: approved, kind/documentation, lgtm

#651 Add vmedia support for workers
  ansible-ipi-install/roles/installer/templates/install-config-virtualmedia.j2
Labels: approved, lgtm, ok-to-test

#662 Fixes edits from Ashley to commit KNIDEPLOY-2088 docs in the downstream.
  documentation/ipi-install/modules/ipi-install-bmc-addressing.adoc
  documentation/ipi-install/modules/ipi-install-creating-a-disconnected-registry.adoc
  documentation/ipi-install/modules/ipi-install-firmware-requirements-for-installing-with-virtual-media.adoc
Labels: approved, kind/documentation, lgtm

#652 Allow IPv6 bmc ip addresses
  ansible-ipi-install/roles/node-prep/tasks/10_validation.yml
Labels: approved, lgtm, needs-ok-to-test

#666 Fixed typos and added a documentation update checkbox.
  .github/pull_request_template.md
Labels: approved, lgtm

#665 Added the module comment first line back in.
  documentation/ipi-install/modules/ipi-install-extracting-the-openshift-installer.adoc
Labels: approved, kind/documentation, lgtm

#667 Add information about repo testing
  ansible-ipi-install/README.md
Labels: approved, lgtm

#664 Fix customize override logic
  ansible-ipi-install/roles/installer/tasks/55_customize_filesystem.yml
Labels: approved, lgtm, needs-ok-to-test

#672 Algha29
  .github/workflows/ansible-lint.yml
  test-requirements.txt
Labels: approved, lgtm

#669 docs(preparing-baremetal-node.adoc): remind version being used for th…
  documentation/ipi-install/modules/ipi-install-preparing-the-bare-metal-node.adoc
Labels: approved, kind/documentation, lgtm

#639 Release 4.7
  utils/build.sh
Labels: approved, lgtm
