Repository openshift-kni/baremetal-deploy, pull requests merged in 2022-01, with the labels that each got.

#828 Add derekhiggins as an approver
  OWNERS
  OWNERS_ALIASES
  ansible-ipi-install/OWNERS
  documentation/OWNERS
Labels: kind/documentation

#820 Update OWNERS_ALIASES
  OWNERS_ALIASES
Labels: lgtm, approved

#809 Add defaults for async deployment timeouts
  ansible-ipi-install/roles/installer/tasks/60_deploy_ocp.yml
Labels: lgtm, ok-to-test, approved
